theme: jekyll-theme-cayman
title: Hi, I'm Tarun Ravi! 👋  <img src="https://bornlicensing.com/wp-content/uploads/2018/01/waving_hand_sign_256.gif" width="50">
show_downloads: true
is_project_page: true
description: ManTech Intern <img src="https://media.giphy.com/media/WUlplcMpOCEmTGBtBW/giphy.gif" width="30"> | Student at Academies of Loudoun <img src="https://media.giphy.com/media/fYSnHlufseco8Fh93Z/giphy.gif" width="30">
