theme: jekyll-theme-cayman
title: Hi, I'm Tarun Ravi! 👋
show_downloads: true
is_project_page: true
description: ManTech Intern | Student at Academies of Loudoun <img src="https://media.giphy.com/media/fYSnHlufseco8Fh93Z/giphy.gif" width="30">
